### ISSUE TITLE
Python 3 compatibility issues in ps3joy and wiimote

### ISSUE THREAD

**Issue by cclauss** [ros2/joystick_drivers#6]
flake8 testing of https://github.com/ros2/joystick_drivers on Python 3.6.3

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./ps3joy/scripts/ps3joy.py:61:29: E999 SyntaxError: invalid syntax
            except Exception, e:
                            ^
./ps3joy/scripts/ps3joy_node.py:68:29: E999 SyntaxError: invalid syntax
            except Exception, e:
                            ^
./ps3joy/scripts/ps3joysim.py:64:33: E999 SyntaxError: invalid syntax
        print "driversim exiting"
                                ^
./wiimote/nodes/wiimote_node.py:116:48: E999 TabError: inconsistent use of tabs and spaces in indentation
	    ClasSender(wiimoteDevice, freq=100).start()
                                               ^
./wiimote/src/wiimote/WIIMote.py:248:5: E999 TabError: inconsistent use of tabs and spaces in indentation
	try:
    ^
./wiimote/src/wiimote/pstat.py:293:27: E999 SyntaxError: invalid syntax
                 if fcn1 <> None:
                          ^
./wiimote/src/wiimote/stats.py:249:37: E999 SyntaxError: invalid syntax
                    raise ValueError, "can't have two dispatches on "+str(t)
                                    ^
./wiimote/src/wiimote/wiimoteTests.py:63:20: E999 SyntaxError: invalid syntax
except WiimoteError, e:
                   ^
./wiimote/src/wiimote/wiistate.py:90:20: E999 SyntaxError: invalid syntax
    self.ascTime = `theTime`
                   ^
./wiimote/src/wiimote/wiiutils.py:61:14: E999 SyntaxError: invalid syntax
    print repr(isGreater)
             ^
10    E999 SyntaxError: invalid syntax
10
```

**Comment by mikaelarguedas** [comment]
None of these packages have been converted to ROS 2 (hence they are not built or tested for ROS 2, hend the presence of `AMENT_IGNORE` files in these packages).

Can you please submit these fixes upstream (https://github.com/ros-drivers/joystick_drivers) and close this PR?
Before being ported to ROS 2, these packages will be synced with upstream.

**Comment by cclauss** [comment]
> This branch is 10 commits ahead, 9 commits behind ros-drivers:master.

**Comment by mikaelarguedas** [comment]
> > This branch is 10 commits ahead, 9 commits behind ros-drivers:master.

Can you clarify how does this prevent the fix to be submitted upstream where the package is maintained (instead of on this unported fork) ?

> Before being ported to ROS 2, these packages will be synced with upstream.

This implies that the repository is not up to date, and that when there is a strong interest in porting those to ROS 2 we will pull the patches. I don't see any patch related to Python 3 on the upstream repository at the moment.

**Comment by cclauss** [comment]
You might want to put all of that into the README.md file when you actually add one to the repo.
